

spring: 
  redis: 
    sentinel:
      master: mymaster
      
      nodes: localhost:6379,localhost:6383,localhost:6384
     
    lettuce:
      shutdown-timeout: 200ms 
      cluster:
        refresh:
          adaptive: true
    